spring:
  application:
    name: video-processor
  datasource:
    url: jdbc:postgresql://database-1.cluster-crzfgagwhurg.us-east-1.rds.amazonaws.com:5432/hackaton
    username: ${POSTGRES_DB}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: hackatonfiap28@gmail.com
    password: "cmlu vtnl jtcg wzrq"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
s3:
  bucket: videos-hackaton
sqs:
  queue:
    url: https://sqs.us-east-1.amazonaws.com/395368505712/video-processing-queue
server:
  port: 8090