spring:
  application:
    name: video-processor
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${USER_EMAIL}
    password: ${PASSWORD_EMAIL}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
          localhost: localhost.localdomain
app:
  mail:
    from: ${EMAIL_REMETENTE}
s3:
  bucket: ${BUCKET}
sqs:
  queue:
    url: ${SQS_QUEUE_URL}
server:
  port: 8090